include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - '**.g.dart'
    - '**.config.dart'
    - '*.generated.dart'
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
