name: university_io_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  dart_frog: ^1.0.0
  drift: ^2.12.1
  get_it: ^7.6.4
  injectable: ^2.3.1
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  drift_dev: ^2.12.1
  injectable_generator: ^2.4.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
