name: Flutter Analyzer
on:
  pull_request:
    branches:
      - master
jobs:
  analyze:
    name: Analyze Pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup project
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze project
        run: |
          flutter analyze